### ISSUE TITLE
Todo last day

### ISSUE THREAD

**Issue by Tom-Bonnike** [Tom-Bonnike/Lunch#16]
- [x] Fix PIN code on `MainViewController`
- [x] Limit hours to 24 / minutes to 60 & autochange focus on `CreateTrainViewController`
- [x] Add analytics
- [x] Fix keyboard going over content on pages with inputs
- [x] Address: Icon Fix
- [x] Overlay Image
- [x] Description Line Height
